### ISSUE TITLE
The translation button on the home page is invalid

### ISSUE THREAD

**Issue by thredreams** [Chever-John/JohnChever-Blog#4]
The problem is as shown above

You can either delete the translation or make a Chinese page

**Comment by Chever-John** [comment]
Thanks for your attention.
However, this website was not used as my leading blog site three months ago.

Because my current consideration for the construction of the website is as follows:
1. cheverjohn. me is the primary domain name of my website.
2. blog.cheverjohn.me is the domain name of my blog website.
3. You can also see says.cheverjohn.me and so on.

I will restart my blog project in a few months but now is not a good time. Because I know that my ability is not enough to pass on knowledge to more people. So let's look forward to the future.
